import aurora_metapool from './aurora/metapool.json';
import aurora_stables_pool from './aurora/stables_pool.json';
import ethereum_curve_address_provider from './ethereum/curve/address_provider.json';
import ethereum_curve_registry from './ethereum/curve/registry.json';
import ethereum_curve_swap from './ethereum/curve/swap.json';
import ethereum_erc20 from './ethereum/erc20.json';
import harmony_hrc20 from './harmony/hrc20.json';
import harmony_curve_tricrypto_zap from './harmony/curve/tricrypto_zap.json';
import moonriver_solarbeam_router from './moonriver/solarbeam_router.json';

export { aurora_metapool };
export { aurora_stables_pool };
export { ethereum_curve_address_provider };
export { ethereum_curve_registry };
export { ethereum_curve_swap };
export { ethereum_erc20 };
export { harmony_hrc20 };
export { harmony_curve_tricrypto_zap };
export { moonriver_solarbeam_router };
