DROP TABLE IF EXISTS cycles CASCADE;
CREATE TABLE cycles (
  id SERIAL PRIMARY KEY NOT NULL,
  node VARCHAR(255) NOT NULL,
  position INTEGER NOT NULL,
  arb_id INTEGER NOT NULL REFERENCES arbs(id) ON DELETE CASCADE
);